version: "3"

networks:
  notification-network:

services:
  plapp-notification-db:
    image: postgres:latest
    container_name: plapp-notification-db
    ports:
      - "5435:5432"
    env_file:
      - postgres.env
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - notification-network


  plapp-notification-service:
    image: maven:latest
    working_dir: $PWD
    container_name: plapp-notification-service
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn spring-boot:run
    networks:
      - notification-network
    depends_on:
      - plapp-notification-db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - plapp-notification-service
    ports:
      - "4005:4000"
    networks:
      - notification-network

volumes:
  database-data:

